version: "3"
services:
    swarmcity_chain_parity:
        build: build
        image: swarmcity_chain_parity
        container_name: "SwarmCityChainParity"
        ports:
            - "8545:8545"
            - "8546:8546"
            - "8180:8180"
            - "8080:8080"
        volumes:
            # Parity config file
            - ./config/:/root/config/
            # Wallet Keys
            - ./data/keys:/root/keys/ethereum
            # Chain data
            - ./data/parity_chain:/root/chain
            # Parity data
            - ./data/parity_basepath:/root/.local/share/io.parity.ethereum
        command: 
             --config /root/config/config.toml
        restart: on-failure

